server:
  port: 10003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cangjingge?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
